# Generated by Django 4.2.7 on 2025-11-20 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airecommendation',
            options={'verbose_name': 'AI рекомендация', 'verbose_name_plural': 'AI рекомендации'},
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='data',
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='is_applied',
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='airecommendation',
            name='type',
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='text',
            field=models.TextField(default='', verbose_name='Рекомендация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL),
        ),
    ]
