# Generated by Django 4.2.7 on 2025-11-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_airecommendation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airecommendation',
            options={'ordering': ['-created_at'], 'verbose_name': 'AI рекомендация', 'verbose_name_plural': 'AI рекомендации'},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={},
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='alert_threshold',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='period_start',
            field=models.DateField(),
        ),
    ]
